### ISSUE TITLE
Rename this module ?

### ISSUE THREAD

**Issue by bcostm** [ARMmbed/mbed-hal-st-stm32cubef4#7]
All source files in this module are those of the STM32F4xx HAL driver. And this driver is placed inside the STM32CubeF4 package.

So, to avoid any misunderstanding, it would be more accurate to rename this module:
mbed-hal-st-**stm32f4xxhal** or mbed-hal-st-**stm32f4xx_hal**

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1094
